# Generated by Django 5.1.2 on 2024-10-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='node',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
