# Generated by Django 5.1.2 on 2024-10-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='text',
            field=models.CharField(max_length=255, verbose_name='text'),
        ),
    ]
