# Generated by Django 5.1.2 on 2024-10-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_system', '0002_alter_node_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='id',
        ),
        migrations.AlterField(
            model_name='node',
            name='key',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='key'),
        ),
    ]
