# Generated by Django 5.1.2 on 2024-10-24 14:16

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages_system', '0002_remove_text_node_delete_node_delete_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='key')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages_system.node')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=0, verbose_name='order')),
                ('text', models.CharField(max_length=255, verbose_name='text')),
                ('node', models.ManyToManyField(related_name='texts', to='pages_system.node', verbose_name='texts')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
