# Generated by Django 5.1.2 on 2024-10-23 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_system', '0003_remove_node_id_alter_node_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='text',
        ),
        migrations.AddField(
            model_name='node',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages_system.node'),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=0, verbose_name='order')),
                ('text', models.CharField(max_length=255, verbose_name='text')),
                ('node', models.ManyToManyField(related_name='texts', to='pages_system.node', verbose_name='texts')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
